// Coach P "Fire" pool — passionate, plain-language intensity.
// 8th-grade words. Real fire, no bro-hype, no fake guru.
// Never condescending. Never shaming. Always addressed as a builder, not a boss.
export const COACH_P_FIRE_EN: string[] = [
  "Get up. The old you doesn't get to vote today.",
  "Nobody is coming. That's the good news.",
  "You don't need permission. You need the first rep.",
  "The plan is the plan. Feelings are late to this meeting.",
  "Tired is a signal, not a stop sign.",
  "Move first. Argue with yourself after.",
  "You wanted change. Change wants work.",
  "The comfort zone is where dreams go to nap.",
  "One hard thing before noon. Then everything else is easy.",
  "You built this body. You get to rebuild it.",
  "Don't wait for the storm to pass. Learn to walk in the rain.",
  "The story ends the way you write it, not the way you feel it.",
  "Small. Loud. Every damn day.",
  "You are the plan. There's no backup.",
  "Sweat is just fear leaving out of the pores.",
  "Cry if you have to. Then load the bar.",
  "Discipline is what you do when nobody's clapping.",
  "You don't get to skip today. Not this one.",
  "Play offense. Defense is exhausting.",
  "The reps you hate are the ones building the man.",
  "Motivation is a bad friend. Show up without it.",
  "Get uncomfortable on purpose. That's the whole game.",
  "The couch is a coffin. Stand up.",
  "Feed the fire, not the fear.",
  "You've been rehearsing weakness. Rehearse strength instead.",
  "Half-effort is a full loss. Give it the whole thing.",
  "Fall in love with the boring reps.",
  "You are one decision away from a different life. Make it.",
  "Excuses are heavy. Put them down.",
  "The man you want to be is on the other side of this workout.",
  "Stop asking if you can. Ask when.",
  "Nobody remembers the day you almost quit. They remember the day you didn't.",
  "Do it scared. Do it tired. Just do it.",
  "You want a lion's life. Train like it.",
  "Talk less. Rep more.",
  "Pain is tuition. Pay it.",
  "The version of you scrolling right now is not the one who wins.",
  "Get sharp. Get honest. Get moving.",
  "Every rep is a vote for the man you say you want to be.",
  "You are not soft. You have been sleeping. Wake up.",
  "This is your comeback. Act like it.",
  "The gym doesn't care about your mood. Show up anyway.",
];

export const COACH_P_FIRE_ES: string[] = [
  "Levántate. El viejo tú no vota hoy.",
  "Nadie viene por ti. Esa es la buena noticia.",
  "No necesitas permiso. Necesitas la primera repetición.",
  "El plan es el plan. Los sentimientos llegan tarde.",
  "Cansado es una señal, no una parada.",
  "Muévete primero. Discute contigo después.",
  "Querías cambiar. El cambio quiere trabajo.",
  "La zona cómoda es donde los sueños se duermen.",
  "Una cosa dura antes del mediodía. Después todo pesa menos.",
  "Tú construiste este cuerpo. Tú lo reconstruyes.",
  "No esperes que pase la tormenta. Aprende a caminar en la lluvia.",
  "La historia termina como la escribes, no como la sientes.",
  "Pequeño. Fuerte. Todos los días.",
  "Tú eres el plan. No hay respaldo.",
  "El sudor es miedo saliendo por los poros.",
  "Llora si tienes que llorar. Después carga la barra.",
  "Disciplina es lo que haces cuando nadie aplaude.",
  "Hoy no se salta. Este día, no.",
  "Ataca. La defensa cansa.",
  "Las repeticiones que odias son las que te construyen.",
  "La motivación es mala amiga. Preséntate sin ella.",
  "Ponte incómodo a propósito. Ese es el juego.",
  "El sofá es un ataúd. Ponte de pie.",
  "Alimenta el fuego, no el miedo.",
  "Has ensayado ser débil. Ensaya ser fuerte.",
  "Medio esfuerzo es una derrota completa. Dalo todo.",
  "Enamórate de las repeticiones aburridas.",
  "Estás a una decisión de otra vida. Tómala.",
  "Las excusas pesan. Suéltalas.",
  "El hombre que quieres ser está al otro lado de este entrenamiento.",
  "Deja de preguntar si puedes. Pregunta cuándo.",
  "Nadie recuerda el día que casi te rendiste. Recuerdan el día que no lo hiciste.",
  "Hazlo con miedo. Hazlo cansado. Hazlo.",
  "Quieres vida de león. Entrena como uno.",
  "Habla menos. Repite más.",
  "El dolor es matrícula. Págala.",
  "La versión que scrollea ahora no es la que gana.",
  "Afílate. Sé honesto. Muévete.",
  "Cada repetición es un voto por el hombre que dices querer ser.",
  "No eres débil. Estabas dormido. Despierta.",
  "Este es tu regreso. Actúa como tal.",
  "Al gimnasio no le importa tu ánimo. Preséntate igual.",
];
