// Coach Grace "Fire" pool — Angels track. Strong AND warm.
// Passionate, sister-to-sister, never aggressive, never condescending.
// 8th-grade words. Real intensity without hardness.
export const COACH_GRACE_FIRE_EN: string[] = [
  "Rise, sister. Today has your name on it.",
  "You were not made to whisper. Speak with your feet.",
  "Soft heart. Steel spine. Both are yours.",
  "The woman you're becoming needs you to show up today.",
  "You don't need permission. You need one honest move.",
  "Move first. Feelings will catch up.",
  "The old story tried to keep you. You are already leaving it.",
  "Small. Steady. Fierce. Every day.",
  "Grace is not weakness. Grace is fire that doesn't need to shout.",
  "You have carried heavier than this. Do it again.",
  "You didn't come this far to only come this far.",
  "Motivation is a liar. Discipline is the truth.",
  "Get up before the doubt does.",
  "The comfort zone is a beautiful cage. Step out.",
  "You are allowed to be tired. You are not required to stay small.",
  "Fall in love with the boring reps. They love you back.",
  "One hard thing today. Then rest, proud.",
  "The mirror is not the enemy. Fear is.",
  "You don't need to be loud. You need to be honest.",
  "Cry if you have to. Then take the next step.",
  "The mother in you is done making excuses for the child in you.",
  "You are not behind. You are becoming, on purpose.",
  "You have been rehearsing weakness. Rehearse power.",
  "Stop shrinking to fit rooms you have outgrown.",
  "You are the answer to your own prayer. Move.",
  "Half-effort is not humility. It's fear in a good dress.",
  "The plan is simple: keep going, gently and on fire.",
  "Every rep is a vote for the woman you say you want to be.",
  "Discipline is love with a schedule.",
  "You do not have to be perfect. You have to be present.",
  "Feed the fire, not the fear.",
  "You were made for this season. Not to survive it — to shape it.",
  "The version of you scrolling is not the one who wins. Get up.",
  "Show up messy. Show up tired. Show up on fire.",
  "You are one honest choice away from a different day.",
  "You do not have to shout to be strong. You have to move.",
  "The next right thing is small and it is holy. Do it.",
  "You have permission to want more. Now go earn it.",
  "Softer with yourself. Louder with the work.",
  "You are not falling apart. You are shedding what does not serve you.",
  "This body carried you here. Thank it. Then push it.",
  "The comeback is not loud. It's daily.",
];

export const COACH_GRACE_FIRE_ES: string[] = [
  "Levántate, hermana. Hoy tiene tu nombre.",
  "No fuiste hecha para susurrar. Habla con tus pies.",
  "Corazón suave. Espalda de acero. Ambos son tuyos.",
  "La mujer en la que te conviertes te necesita hoy.",
  "No necesitas permiso. Necesitas un solo movimiento honesto.",
  "Muévete primero. Los sentimientos te alcanzan.",
  "La vieja historia trató de quedarse contigo. Ya la estás dejando.",
  "Pequeña. Constante. Feroz. Todos los días.",
  "La gracia no es debilidad. Es fuego que no necesita gritar.",
  "Has cargado más pesado que esto. Hazlo otra vez.",
  "No llegaste hasta aquí para llegar solo hasta aquí.",
  "La motivación miente. La disciplina dice la verdad.",
  "Levántate antes que la duda.",
  "La zona cómoda es una jaula bonita. Sal.",
  "Puedes estar cansada. No estás obligada a quedarte pequeña.",
  "Enamórate de las repeticiones aburridas. Ellas te aman de vuelta.",
  "Una cosa dura hoy. Después descansa, orgullosa.",
  "El espejo no es el enemigo. El miedo lo es.",
  "No necesitas ser ruidosa. Necesitas ser honesta.",
  "Llora si necesitas llorar. Después da el siguiente paso.",
  "La madre en ti ya no da excusas por la niña en ti.",
  "No estás atrasada. Te estás convirtiendo, a propósito.",
  "Has ensayado la debilidad. Ensaya el poder.",
  "Deja de encogerte para caber en cuartos que ya superaste.",
  "Eres la respuesta a tu propia oración. Muévete.",
  "Medio esfuerzo no es humildad. Es miedo bien vestido.",
  "El plan es simple: sigue, suave y con fuego.",
  "Cada repetición es un voto por la mujer que dices querer ser.",
  "Disciplina es amor con horario.",
  "No tienes que ser perfecta. Tienes que estar presente.",
  "Alimenta el fuego, no el miedo.",
  "Fuiste hecha para esta temporada. No para sobrevivirla — para darle forma.",
  "La versión que scrollea no es la que gana. Levántate.",
  "Preséntate desordenada. Cansada. Con fuego.",
  "Estás a una elección honesta de otro día.",
  "No tienes que gritar para ser fuerte. Tienes que moverte.",
  "Lo siguiente correcto es pequeño y es sagrado. Hazlo.",
  "Tienes permiso para querer más. Ahora gánalo.",
  "Más suave contigo. Más fuerte con el trabajo.",
  "No te estás rompiendo. Estás soltando lo que no te sirve.",
  "Este cuerpo te trajo aquí. Agradécele. Después empújalo.",
  "El regreso no es ruidoso. Es diario.",
];
