/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as ScreenerFailRouteImport } from './routes/screener-fail'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as QaRouteImport } from './routes/qa'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CourseRouteImport } from './routes/course'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout_.return'
import { Route as AppWelcomeRouteImport } from './routes/app.welcome'
import { Route as AppUpgradeRouteImport } from './routes/app.upgrade'
import { Route as AppTodayRouteImport } from './routes/app.today'
import { Route as AppSpiritRouteImport } from './routes/app.spirit'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppRedeemRouteImport } from './routes/app.redeem'
import { Route as AppReadinessRouteImport } from './routes/app.readiness'
import { Route as AppProtocolRouteImport } from './routes/app.protocol'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppPeptidesRouteImport } from './routes/app.peptides'
import { Route as AppOutdoorRouteImport } from './routes/app.outdoor'
import { Route as AppNutritionRouteImport } from './routes/app.nutrition'
import { Route as AppLabsRouteImport } from './routes/app.labs'
import { Route as AppJournalRouteImport } from './routes/app.journal'
import { Route as AppIdentityRouteImport } from './routes/app.identity'
import { Route as AppGenderRequiredRouteImport } from './routes/app.gender-required'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppCheckinRouteImport } from './routes/app.checkin'
import { Route as AppBreatheRouteImport } from './routes/app.breathe'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AdminUpsellEmailsRouteImport } from './routes/admin.upsell-emails'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminPinRouteImport } from './routes/admin.pin'
import { Route as AdminPerksRouteImport } from './routes/admin.perks'
import { Route as AdminMoneyRouteImport } from './routes/admin.money'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminMealsRouteImport } from './routes/admin.meals'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminCourseRouteImport } from './routes/admin.course'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminConsultRouteImport } from './routes/admin.consult'
import { Route as AdminCoachingRouteImport } from './routes/admin.coaching'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as DotwellKnownAppleDeveloperMerchantidDomainAssociationRouteImport } from './routes/[.]well-known.apple-developer-merchantid-domain-association'
import { Route as AppConsultIndexRouteImport } from './routes/app.consult.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AppProtocolHistoryRouteImport } from './routes/app.protocol.history'
import { Route as AppNutritionMogulBonusesRouteImport } from './routes/app.nutrition.mogul-bonuses'
import { Route as AppNutritionAcademyRouteImport } from './routes/app.nutrition.academy'
import { Route as AppNutritionSlugRouteImport } from './routes/app.nutrition.$slug'
import { Route as AppMirrorIdRouteImport } from './routes/app.mirror.$id'
import { Route as AppConsultSeatRouteImport } from './routes/app.consult.seat'
import { Route as AppConsultApplyRouteImport } from './routes/app.consult.apply'
import { Route as AppCheckinTodayRouteImport } from './routes/app.checkin.today'
import { Route as ApiPublicCollectRouteImport } from './routes/api/public/collect'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AppNutritionLessonsSlugRouteImport } from './routes/app.nutrition.lessons.$slug'
import { Route as ApiPublicPerksVerifyRouteImport } from './routes/api/public/perks.verify'
import { Route as ApiPublicMogulBonusesSlugRouteImport } from './routes/api/public/mogul-bonuses.$slug'
import { Route as ApiPublicHooksUpsellCampaignsRouteImport } from './routes/api/public/hooks/upsell-campaigns'
import { Route as ApiPublicHooksTrialEndingReminderRouteImport } from './routes/api/public/hooks/trial-ending-reminder'
import { Route as ApiPublicHooksStripeRouteImport } from './routes/api/public/hooks/stripe'
import { Route as ApiPublicHooksRenewalReminderRouteImport } from './routes/api/public/hooks/renewal-reminder'
import { Route as ApiPublicHooksReengagementRouteImport } from './routes/api/public/hooks/reengagement'
import { Route as ApiPublicHooksMorningCheckinNudgeRouteImport } from './routes/api/public/hooks/morning-checkin-nudge'
import { Route as ApiPublicHooksMedicationRemindersRouteImport } from './routes/api/public/hooks/medication-reminders'
import { Route as ApiPublicHooksMealRemindersRouteImport } from './routes/api/public/hooks/meal-reminders'
import { Route as ApiPublicHooksDailyEnqueueRouteImport } from './routes/api/public/hooks/daily-enqueue'
import { Route as ApiPublicHooksCoachDigestRouteImport } from './routes/api/public/hooks/coach-digest'
import { Route as ApiPublicOauthProviderCallbackRouteImport } from './routes/api/public/oauth.$provider.callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerFailRoute = ScreenerFailRouteImport.update({
  id: '/screener-fail',
  path: '/screener-fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout_/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppSpiritRoute = AppSpiritRouteImport.update({
  id: '/spirit',
  path: '/spirit',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppRedeemRoute = AppRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => AppRoute,
} as any)
const AppReadinessRoute = AppReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocolRoute = AppProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPeptidesRoute = AppPeptidesRouteImport.update({
  id: '/peptides',
  path: '/peptides',
  getParentRoute: () => AppRoute,
} as any)
const AppOutdoorRoute = AppOutdoorRouteImport.update({
  id: '/outdoor',
  path: '/outdoor',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppLabsRoute = AppLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityRoute = AppIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AppRoute,
} as any)
const AppGenderRequiredRoute = AppGenderRequiredRouteImport.update({
  id: '/gender-required',
  path: '/gender-required',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppBreatheRoute = AppBreatheRouteImport.update({
  id: '/breathe',
  path: '/breathe',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AdminUpsellEmailsRoute = AdminUpsellEmailsRouteImport.update({
  id: '/upsell-emails',
  path: '/upsell-emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPinRoute = AdminPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerksRoute = AdminPerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoneyRoute = AdminMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMealsRoute = AdminMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourseRoute = AdminCourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultRoute = AdminConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachingRoute = AdminCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute =
  DotwellKnownAppleDeveloperMerchantidDomainAssociationRouteImport.update({
    id: '/.well-known/apple-developer-merchantid-domain-association',
    path: '/.well-known/apple-developer-merchantid-domain-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppConsultIndexRoute = AppConsultIndexRouteImport.update({
  id: '/consult/',
  path: '/consult/',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtocolHistoryRoute = AppProtocolHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppProtocolRoute,
} as any)
const AppNutritionMogulBonusesRoute =
  AppNutritionMogulBonusesRouteImport.update({
    id: '/mogul-bonuses',
    path: '/mogul-bonuses',
    getParentRoute: () => AppNutritionRoute,
  } as any)
const AppNutritionAcademyRoute = AppNutritionAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AppNutritionRoute,
} as any)
const AppNutritionSlugRoute = AppNutritionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppNutritionRoute,
} as any)
const AppMirrorIdRoute = AppMirrorIdRouteImport.update({
  id: '/mirror/$id',
  path: '/mirror/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultSeatRoute = AppConsultSeatRouteImport.update({
  id: '/consult/seat',
  path: '/consult/seat',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultApplyRoute = AppConsultApplyRouteImport.update({
  id: '/consult/apply',
  path: '/consult/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinTodayRoute = AppCheckinTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppCheckinRoute,
} as any)
const ApiPublicCollectRoute = ApiPublicCollectRouteImport.update({
  id: '/api/public/collect',
  path: '/api/public/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppNutritionLessonsSlugRoute = AppNutritionLessonsSlugRouteImport.update({
  id: '/lessons/$slug',
  path: '/lessons/$slug',
  getParentRoute: () => AppNutritionRoute,
} as any)
const ApiPublicPerksVerifyRoute = ApiPublicPerksVerifyRouteImport.update({
  id: '/api/public/perks/verify',
  path: '/api/public/perks/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMogulBonusesSlugRoute =
  ApiPublicMogulBonusesSlugRouteImport.update({
    id: '/api/public/mogul-bonuses/$slug',
    path: '/api/public/mogul-bonuses/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksUpsellCampaignsRoute =
  ApiPublicHooksUpsellCampaignsRouteImport.update({
    id: '/api/public/hooks/upsell-campaigns',
    path: '/api/public/hooks/upsell-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrialEndingReminderRoute =
  ApiPublicHooksTrialEndingReminderRouteImport.update({
    id: '/api/public/hooks/trial-ending-reminder',
    path: '/api/public/hooks/trial-ending-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStripeRoute = ApiPublicHooksStripeRouteImport.update({
  id: '/api/public/hooks/stripe',
  path: '/api/public/hooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRenewalReminderRoute =
  ApiPublicHooksRenewalReminderRouteImport.update({
    id: '/api/public/hooks/renewal-reminder',
    path: '/api/public/hooks/renewal-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReengagementRoute =
  ApiPublicHooksReengagementRouteImport.update({
    id: '/api/public/hooks/reengagement',
    path: '/api/public/hooks/reengagement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMorningCheckinNudgeRoute =
  ApiPublicHooksMorningCheckinNudgeRouteImport.update({
    id: '/api/public/hooks/morning-checkin-nudge',
    path: '/api/public/hooks/morning-checkin-nudge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMedicationRemindersRoute =
  ApiPublicHooksMedicationRemindersRouteImport.update({
    id: '/api/public/hooks/medication-reminders',
    path: '/api/public/hooks/medication-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMealRemindersRoute =
  ApiPublicHooksMealRemindersRouteImport.update({
    id: '/api/public/hooks/meal-reminders',
    path: '/api/public/hooks/meal-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyEnqueueRoute =
  ApiPublicHooksDailyEnqueueRouteImport.update({
    id: '/api/public/hooks/daily-enqueue',
    path: '/api/public/hooks/daily-enqueue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCoachDigestRoute =
  ApiPublicHooksCoachDigestRouteImport.update({
    id: '/api/public/hooks/coach-digest',
    path: '/api/public/hooks/coach-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthProviderCallbackRoute =
  ApiPublicOauthProviderCallbackRouteImport.update({
    id: '/api/public/oauth/$provider/callback',
    path: '/api/public/oauth/$provider/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/course': typeof CourseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/qa': typeof QaRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screener-fail': typeof ScreenerFailRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-developer-merchantid-domain-association': typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/coaching': typeof AdminCoachingRoute
  '/admin/consult': typeof AdminConsultRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/course': typeof AdminCourseRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/perks': typeof AdminPerksRoute
  '/admin/pin': typeof AdminPinRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/upsell-emails': typeof AdminUpsellEmailsRoute
  '/app/account': typeof AppAccountRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/breathe': typeof AppBreatheRoute
  '/app/checkin': typeof AppCheckinRouteWithChildren
  '/app/coach': typeof AppCoachRoute
  '/app/gender-required': typeof AppGenderRequiredRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/journal': typeof AppJournalRoute
  '/app/labs': typeof AppLabsRoute
  '/app/nutrition': typeof AppNutritionRouteWithChildren
  '/app/outdoor': typeof AppOutdoorRoute
  '/app/peptides': typeof AppPeptidesRoute
  '/app/plan': typeof AppPlanRoute
  '/app/progress': typeof AppProgressRoute
  '/app/protocol': typeof AppProtocolRouteWithChildren
  '/app/readiness': typeof AppReadinessRoute
  '/app/redeem': typeof AppRedeemRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spirit': typeof AppSpiritRoute
  '/app/today': typeof AppTodayRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/app/checkin/today': typeof AppCheckinTodayRoute
  '/app/consult/apply': typeof AppConsultApplyRoute
  '/app/consult/seat': typeof AppConsultSeatRoute
  '/app/mirror/$id': typeof AppMirrorIdRoute
  '/app/nutrition/$slug': typeof AppNutritionSlugRoute
  '/app/nutrition/academy': typeof AppNutritionAcademyRoute
  '/app/nutrition/mogul-bonuses': typeof AppNutritionMogulBonusesRoute
  '/app/protocol/history': typeof AppProtocolHistoryRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/consult/': typeof AppConsultIndexRoute
  '/api/public/hooks/coach-digest': typeof ApiPublicHooksCoachDigestRoute
  '/api/public/hooks/daily-enqueue': typeof ApiPublicHooksDailyEnqueueRoute
  '/api/public/hooks/meal-reminders': typeof ApiPublicHooksMealRemindersRoute
  '/api/public/hooks/medication-reminders': typeof ApiPublicHooksMedicationRemindersRoute
  '/api/public/hooks/morning-checkin-nudge': typeof ApiPublicHooksMorningCheckinNudgeRoute
  '/api/public/hooks/reengagement': typeof ApiPublicHooksReengagementRoute
  '/api/public/hooks/renewal-reminder': typeof ApiPublicHooksRenewalReminderRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/trial-ending-reminder': typeof ApiPublicHooksTrialEndingReminderRoute
  '/api/public/hooks/upsell-campaigns': typeof ApiPublicHooksUpsellCampaignsRoute
  '/api/public/mogul-bonuses/$slug': typeof ApiPublicMogulBonusesSlugRoute
  '/api/public/perks/verify': typeof ApiPublicPerksVerifyRoute
  '/app/nutrition/lessons/$slug': typeof AppNutritionLessonsSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/oauth/$provider/callback': typeof ApiPublicOauthProviderCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/course': typeof CourseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/qa': typeof QaRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screener-fail': typeof ScreenerFailRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-developer-merchantid-domain-association': typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/coaching': typeof AdminCoachingRoute
  '/admin/consult': typeof AdminConsultRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/course': typeof AdminCourseRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/perks': typeof AdminPerksRoute
  '/admin/pin': typeof AdminPinRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/upsell-emails': typeof AdminUpsellEmailsRoute
  '/app/account': typeof AppAccountRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/breathe': typeof AppBreatheRoute
  '/app/checkin': typeof AppCheckinRouteWithChildren
  '/app/coach': typeof AppCoachRoute
  '/app/gender-required': typeof AppGenderRequiredRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/journal': typeof AppJournalRoute
  '/app/labs': typeof AppLabsRoute
  '/app/nutrition': typeof AppNutritionRouteWithChildren
  '/app/outdoor': typeof AppOutdoorRoute
  '/app/peptides': typeof AppPeptidesRoute
  '/app/plan': typeof AppPlanRoute
  '/app/progress': typeof AppProgressRoute
  '/app/protocol': typeof AppProtocolRouteWithChildren
  '/app/readiness': typeof AppReadinessRoute
  '/app/redeem': typeof AppRedeemRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spirit': typeof AppSpiritRoute
  '/app/today': typeof AppTodayRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/app/checkin/today': typeof AppCheckinTodayRoute
  '/app/consult/apply': typeof AppConsultApplyRoute
  '/app/consult/seat': typeof AppConsultSeatRoute
  '/app/mirror/$id': typeof AppMirrorIdRoute
  '/app/nutrition/$slug': typeof AppNutritionSlugRoute
  '/app/nutrition/academy': typeof AppNutritionAcademyRoute
  '/app/nutrition/mogul-bonuses': typeof AppNutritionMogulBonusesRoute
  '/app/protocol/history': typeof AppProtocolHistoryRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/consult': typeof AppConsultIndexRoute
  '/api/public/hooks/coach-digest': typeof ApiPublicHooksCoachDigestRoute
  '/api/public/hooks/daily-enqueue': typeof ApiPublicHooksDailyEnqueueRoute
  '/api/public/hooks/meal-reminders': typeof ApiPublicHooksMealRemindersRoute
  '/api/public/hooks/medication-reminders': typeof ApiPublicHooksMedicationRemindersRoute
  '/api/public/hooks/morning-checkin-nudge': typeof ApiPublicHooksMorningCheckinNudgeRoute
  '/api/public/hooks/reengagement': typeof ApiPublicHooksReengagementRoute
  '/api/public/hooks/renewal-reminder': typeof ApiPublicHooksRenewalReminderRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/trial-ending-reminder': typeof ApiPublicHooksTrialEndingReminderRoute
  '/api/public/hooks/upsell-campaigns': typeof ApiPublicHooksUpsellCampaignsRoute
  '/api/public/mogul-bonuses/$slug': typeof ApiPublicMogulBonusesSlugRoute
  '/api/public/perks/verify': typeof ApiPublicPerksVerifyRoute
  '/app/nutrition/lessons/$slug': typeof AppNutritionLessonsSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/oauth/$provider/callback': typeof ApiPublicOauthProviderCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/course': typeof CourseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/qa': typeof QaRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screener-fail': typeof ScreenerFailRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-developer-merchantid-domain-association': typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/coaching': typeof AdminCoachingRoute
  '/admin/consult': typeof AdminConsultRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/course': typeof AdminCourseRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/money': typeof AdminMoneyRoute
  '/admin/perks': typeof AdminPerksRoute
  '/admin/pin': typeof AdminPinRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/upsell-emails': typeof AdminUpsellEmailsRoute
  '/app/account': typeof AppAccountRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/breathe': typeof AppBreatheRoute
  '/app/checkin': typeof AppCheckinRouteWithChildren
  '/app/coach': typeof AppCoachRoute
  '/app/gender-required': typeof AppGenderRequiredRoute
  '/app/identity': typeof AppIdentityRoute
  '/app/journal': typeof AppJournalRoute
  '/app/labs': typeof AppLabsRoute
  '/app/nutrition': typeof AppNutritionRouteWithChildren
  '/app/outdoor': typeof AppOutdoorRoute
  '/app/peptides': typeof AppPeptidesRoute
  '/app/plan': typeof AppPlanRoute
  '/app/progress': typeof AppProgressRoute
  '/app/protocol': typeof AppProtocolRouteWithChildren
  '/app/readiness': typeof AppReadinessRoute
  '/app/redeem': typeof AppRedeemRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/spirit': typeof AppSpiritRoute
  '/app/today': typeof AppTodayRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/checkout_/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/collect': typeof ApiPublicCollectRoute
  '/app/checkin/today': typeof AppCheckinTodayRoute
  '/app/consult/apply': typeof AppConsultApplyRoute
  '/app/consult/seat': typeof AppConsultSeatRoute
  '/app/mirror/$id': typeof AppMirrorIdRoute
  '/app/nutrition/$slug': typeof AppNutritionSlugRoute
  '/app/nutrition/academy': typeof AppNutritionAcademyRoute
  '/app/nutrition/mogul-bonuses': typeof AppNutritionMogulBonusesRoute
  '/app/protocol/history': typeof AppProtocolHistoryRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/consult/': typeof AppConsultIndexRoute
  '/api/public/hooks/coach-digest': typeof ApiPublicHooksCoachDigestRoute
  '/api/public/hooks/daily-enqueue': typeof ApiPublicHooksDailyEnqueueRoute
  '/api/public/hooks/meal-reminders': typeof ApiPublicHooksMealRemindersRoute
  '/api/public/hooks/medication-reminders': typeof ApiPublicHooksMedicationRemindersRoute
  '/api/public/hooks/morning-checkin-nudge': typeof ApiPublicHooksMorningCheckinNudgeRoute
  '/api/public/hooks/reengagement': typeof ApiPublicHooksReengagementRoute
  '/api/public/hooks/renewal-reminder': typeof ApiPublicHooksRenewalReminderRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/api/public/hooks/trial-ending-reminder': typeof ApiPublicHooksTrialEndingReminderRoute
  '/api/public/hooks/upsell-campaigns': typeof ApiPublicHooksUpsellCampaignsRoute
  '/api/public/mogul-bonuses/$slug': typeof ApiPublicMogulBonusesSlugRoute
  '/api/public/perks/verify': typeof ApiPublicPerksVerifyRoute
  '/app/nutrition/lessons/$slug': typeof AppNutritionLessonsSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/oauth/$provider/callback': typeof ApiPublicOauthProviderCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/checkout'
    | '/course'
    | '/forgot-password'
    | '/legal'
    | '/login'
    | '/no-access'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/qa'
    | '/refunds'
    | '/reset-password'
    | '/screener-fail'
    | '/subscribe'
    | '/terms'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/admin/clients'
    | '/admin/coaching'
    | '/admin/consult'
    | '/admin/content'
    | '/admin/course'
    | '/admin/features'
    | '/admin/meals'
    | '/admin/members'
    | '/admin/money'
    | '/admin/perks'
    | '/admin/pin'
    | '/admin/support'
    | '/admin/upsell-emails'
    | '/app/account'
    | '/app/achievements'
    | '/app/billing'
    | '/app/breathe'
    | '/app/checkin'
    | '/app/coach'
    | '/app/gender-required'
    | '/app/identity'
    | '/app/journal'
    | '/app/labs'
    | '/app/nutrition'
    | '/app/outdoor'
    | '/app/peptides'
    | '/app/plan'
    | '/app/progress'
    | '/app/protocol'
    | '/app/readiness'
    | '/app/redeem'
    | '/app/review'
    | '/app/settings'
    | '/app/spirit'
    | '/app/today'
    | '/app/upgrade'
    | '/app/welcome'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/admin/'
    | '/app/'
    | '/api/public/collect'
    | '/app/checkin/today'
    | '/app/consult/apply'
    | '/app/consult/seat'
    | '/app/mirror/$id'
    | '/app/nutrition/$slug'
    | '/app/nutrition/academy'
    | '/app/nutrition/mogul-bonuses'
    | '/app/protocol/history'
    | '/lovable/email/suppression'
    | '/app/consult/'
    | '/api/public/hooks/coach-digest'
    | '/api/public/hooks/daily-enqueue'
    | '/api/public/hooks/meal-reminders'
    | '/api/public/hooks/medication-reminders'
    | '/api/public/hooks/morning-checkin-nudge'
    | '/api/public/hooks/reengagement'
    | '/api/public/hooks/renewal-reminder'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/trial-ending-reminder'
    | '/api/public/hooks/upsell-campaigns'
    | '/api/public/mogul-bonuses/$slug'
    | '/api/public/perks/verify'
    | '/app/nutrition/lessons/$slug'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/oauth/$provider/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/course'
    | '/forgot-password'
    | '/legal'
    | '/login'
    | '/no-access'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/qa'
    | '/refunds'
    | '/reset-password'
    | '/screener-fail'
    | '/subscribe'
    | '/terms'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/admin/clients'
    | '/admin/coaching'
    | '/admin/consult'
    | '/admin/content'
    | '/admin/course'
    | '/admin/features'
    | '/admin/meals'
    | '/admin/members'
    | '/admin/money'
    | '/admin/perks'
    | '/admin/pin'
    | '/admin/support'
    | '/admin/upsell-emails'
    | '/app/account'
    | '/app/achievements'
    | '/app/billing'
    | '/app/breathe'
    | '/app/checkin'
    | '/app/coach'
    | '/app/gender-required'
    | '/app/identity'
    | '/app/journal'
    | '/app/labs'
    | '/app/nutrition'
    | '/app/outdoor'
    | '/app/peptides'
    | '/app/plan'
    | '/app/progress'
    | '/app/protocol'
    | '/app/readiness'
    | '/app/redeem'
    | '/app/review'
    | '/app/settings'
    | '/app/spirit'
    | '/app/today'
    | '/app/upgrade'
    | '/app/welcome'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/admin'
    | '/app'
    | '/api/public/collect'
    | '/app/checkin/today'
    | '/app/consult/apply'
    | '/app/consult/seat'
    | '/app/mirror/$id'
    | '/app/nutrition/$slug'
    | '/app/nutrition/academy'
    | '/app/nutrition/mogul-bonuses'
    | '/app/protocol/history'
    | '/lovable/email/suppression'
    | '/app/consult'
    | '/api/public/hooks/coach-digest'
    | '/api/public/hooks/daily-enqueue'
    | '/api/public/hooks/meal-reminders'
    | '/api/public/hooks/medication-reminders'
    | '/api/public/hooks/morning-checkin-nudge'
    | '/api/public/hooks/reengagement'
    | '/api/public/hooks/renewal-reminder'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/trial-ending-reminder'
    | '/api/public/hooks/upsell-campaigns'
    | '/api/public/mogul-bonuses/$slug'
    | '/api/public/perks/verify'
    | '/app/nutrition/lessons/$slug'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/oauth/$provider/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/checkout'
    | '/course'
    | '/forgot-password'
    | '/legal'
    | '/login'
    | '/no-access'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/qa'
    | '/refunds'
    | '/reset-password'
    | '/screener-fail'
    | '/subscribe'
    | '/terms'
    | '/.well-known/apple-developer-merchantid-domain-association'
    | '/admin/clients'
    | '/admin/coaching'
    | '/admin/consult'
    | '/admin/content'
    | '/admin/course'
    | '/admin/features'
    | '/admin/meals'
    | '/admin/members'
    | '/admin/money'
    | '/admin/perks'
    | '/admin/pin'
    | '/admin/support'
    | '/admin/upsell-emails'
    | '/app/account'
    | '/app/achievements'
    | '/app/billing'
    | '/app/breathe'
    | '/app/checkin'
    | '/app/coach'
    | '/app/gender-required'
    | '/app/identity'
    | '/app/journal'
    | '/app/labs'
    | '/app/nutrition'
    | '/app/outdoor'
    | '/app/peptides'
    | '/app/plan'
    | '/app/progress'
    | '/app/protocol'
    | '/app/readiness'
    | '/app/redeem'
    | '/app/review'
    | '/app/settings'
    | '/app/spirit'
    | '/app/today'
    | '/app/upgrade'
    | '/app/welcome'
    | '/checkout_/return'
    | '/email/unsubscribe'
    | '/admin/'
    | '/app/'
    | '/api/public/collect'
    | '/app/checkin/today'
    | '/app/consult/apply'
    | '/app/consult/seat'
    | '/app/mirror/$id'
    | '/app/nutrition/$slug'
    | '/app/nutrition/academy'
    | '/app/nutrition/mogul-bonuses'
    | '/app/protocol/history'
    | '/lovable/email/suppression'
    | '/app/consult/'
    | '/api/public/hooks/coach-digest'
    | '/api/public/hooks/daily-enqueue'
    | '/api/public/hooks/meal-reminders'
    | '/api/public/hooks/medication-reminders'
    | '/api/public/hooks/morning-checkin-nudge'
    | '/api/public/hooks/reengagement'
    | '/api/public/hooks/renewal-reminder'
    | '/api/public/hooks/stripe'
    | '/api/public/hooks/trial-ending-reminder'
    | '/api/public/hooks/upsell-campaigns'
    | '/api/public/mogul-bonuses/$slug'
    | '/api/public/perks/verify'
    | '/app/nutrition/lessons/$slug'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/oauth/$provider/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CourseRoute: typeof CourseRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  QaRoute: typeof QaRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScreenerFailRoute: typeof ScreenerFailRoute
  SubscribeRoute: typeof SubscribeRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute: typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicCollectRoute: typeof ApiPublicCollectRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksCoachDigestRoute: typeof ApiPublicHooksCoachDigestRoute
  ApiPublicHooksDailyEnqueueRoute: typeof ApiPublicHooksDailyEnqueueRoute
  ApiPublicHooksMealRemindersRoute: typeof ApiPublicHooksMealRemindersRoute
  ApiPublicHooksMedicationRemindersRoute: typeof ApiPublicHooksMedicationRemindersRoute
  ApiPublicHooksMorningCheckinNudgeRoute: typeof ApiPublicHooksMorningCheckinNudgeRoute
  ApiPublicHooksReengagementRoute: typeof ApiPublicHooksReengagementRoute
  ApiPublicHooksRenewalReminderRoute: typeof ApiPublicHooksRenewalReminderRoute
  ApiPublicHooksStripeRoute: typeof ApiPublicHooksStripeRoute
  ApiPublicHooksTrialEndingReminderRoute: typeof ApiPublicHooksTrialEndingReminderRoute
  ApiPublicHooksUpsellCampaignsRoute: typeof ApiPublicHooksUpsellCampaignsRoute
  ApiPublicMogulBonusesSlugRoute: typeof ApiPublicMogulBonusesSlugRoute
  ApiPublicPerksVerifyRoute: typeof ApiPublicPerksVerifyRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicOauthProviderCallbackRoute: typeof ApiPublicOauthProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener-fail': {
      id: '/screener-fail'
      path: '/screener-fail'
      fullPath: '/screener-fail'
      preLoaderRoute: typeof ScreenerFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/return': {
      id: '/checkout_/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/welcome': {
      id: '/app/welcome'
      path: '/welcome'
      fullPath: '/app/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spirit': {
      id: '/app/spirit'
      path: '/spirit'
      fullPath: '/app/spirit'
      preLoaderRoute: typeof AppSpiritRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/redeem': {
      id: '/app/redeem'
      path: '/redeem'
      fullPath: '/app/redeem'
      preLoaderRoute: typeof AppRedeemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/readiness': {
      id: '/app/readiness'
      path: '/readiness'
      fullPath: '/app/readiness'
      preLoaderRoute: typeof AppReadinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/protocol': {
      id: '/app/protocol'
      path: '/protocol'
      fullPath: '/app/protocol'
      preLoaderRoute: typeof AppProtocolRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/peptides': {
      id: '/app/peptides'
      path: '/peptides'
      fullPath: '/app/peptides'
      preLoaderRoute: typeof AppPeptidesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outdoor': {
      id: '/app/outdoor'
      path: '/outdoor'
      fullPath: '/app/outdoor'
      preLoaderRoute: typeof AppOutdoorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutrition': {
      id: '/app/nutrition'
      path: '/nutrition'
      fullPath: '/app/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/labs': {
      id: '/app/labs'
      path: '/labs'
      fullPath: '/app/labs'
      preLoaderRoute: typeof AppLabsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity': {
      id: '/app/identity'
      path: '/identity'
      fullPath: '/app/identity'
      preLoaderRoute: typeof AppIdentityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gender-required': {
      id: '/app/gender-required'
      path: '/gender-required'
      fullPath: '/app/gender-required'
      preLoaderRoute: typeof AppGenderRequiredRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin': {
      id: '/app/checkin'
      path: '/checkin'
      fullPath: '/app/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/breathe': {
      id: '/app/breathe'
      path: '/breathe'
      fullPath: '/app/breathe'
      preLoaderRoute: typeof AppBreatheRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/upsell-emails': {
      id: '/admin/upsell-emails'
      path: '/upsell-emails'
      fullPath: '/admin/upsell-emails'
      preLoaderRoute: typeof AdminUpsellEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pin': {
      id: '/admin/pin'
      path: '/pin'
      fullPath: '/admin/pin'
      preLoaderRoute: typeof AdminPinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perks': {
      id: '/admin/perks'
      path: '/perks'
      fullPath: '/admin/perks'
      preLoaderRoute: typeof AdminPerksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/money': {
      id: '/admin/money'
      path: '/money'
      fullPath: '/admin/money'
      preLoaderRoute: typeof AdminMoneyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meals': {
      id: '/admin/meals'
      path: '/meals'
      fullPath: '/admin/meals'
      preLoaderRoute: typeof AdminMealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/course': {
      id: '/admin/course'
      path: '/course'
      fullPath: '/admin/course'
      preLoaderRoute: typeof AdminCourseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consult': {
      id: '/admin/consult'
      path: '/consult'
      fullPath: '/admin/consult'
      preLoaderRoute: typeof AdminConsultRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coaching': {
      id: '/admin/coaching'
      path: '/coaching'
      fullPath: '/admin/coaching'
      preLoaderRoute: typeof AdminCoachingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/apple-developer-merchantid-domain-association': {
      id: '/.well-known/apple-developer-merchantid-domain-association'
      path: '/.well-known/apple-developer-merchantid-domain-association'
      fullPath: '/.well-known/apple-developer-merchantid-domain-association'
      preLoaderRoute: typeof DotwellKnownAppleDeveloperMerchantidDomainAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/consult/': {
      id: '/app/consult/'
      path: '/consult'
      fullPath: '/app/consult/'
      preLoaderRoute: typeof AppConsultIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/protocol/history': {
      id: '/app/protocol/history'
      path: '/history'
      fullPath: '/app/protocol/history'
      preLoaderRoute: typeof AppProtocolHistoryRouteImport
      parentRoute: typeof AppProtocolRoute
    }
    '/app/nutrition/mogul-bonuses': {
      id: '/app/nutrition/mogul-bonuses'
      path: '/mogul-bonuses'
      fullPath: '/app/nutrition/mogul-bonuses'
      preLoaderRoute: typeof AppNutritionMogulBonusesRouteImport
      parentRoute: typeof AppNutritionRoute
    }
    '/app/nutrition/academy': {
      id: '/app/nutrition/academy'
      path: '/academy'
      fullPath: '/app/nutrition/academy'
      preLoaderRoute: typeof AppNutritionAcademyRouteImport
      parentRoute: typeof AppNutritionRoute
    }
    '/app/nutrition/$slug': {
      id: '/app/nutrition/$slug'
      path: '/$slug'
      fullPath: '/app/nutrition/$slug'
      preLoaderRoute: typeof AppNutritionSlugRouteImport
      parentRoute: typeof AppNutritionRoute
    }
    '/app/mirror/$id': {
      id: '/app/mirror/$id'
      path: '/mirror/$id'
      fullPath: '/app/mirror/$id'
      preLoaderRoute: typeof AppMirrorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consult/seat': {
      id: '/app/consult/seat'
      path: '/consult/seat'
      fullPath: '/app/consult/seat'
      preLoaderRoute: typeof AppConsultSeatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consult/apply': {
      id: '/app/consult/apply'
      path: '/consult/apply'
      fullPath: '/app/consult/apply'
      preLoaderRoute: typeof AppConsultApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkin/today': {
      id: '/app/checkin/today'
      path: '/today'
      fullPath: '/app/checkin/today'
      preLoaderRoute: typeof AppCheckinTodayRouteImport
      parentRoute: typeof AppCheckinRoute
    }
    '/api/public/collect': {
      id: '/api/public/collect'
      path: '/api/public/collect'
      fullPath: '/api/public/collect'
      preLoaderRoute: typeof ApiPublicCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/nutrition/lessons/$slug': {
      id: '/app/nutrition/lessons/$slug'
      path: '/lessons/$slug'
      fullPath: '/app/nutrition/lessons/$slug'
      preLoaderRoute: typeof AppNutritionLessonsSlugRouteImport
      parentRoute: typeof AppNutritionRoute
    }
    '/api/public/perks/verify': {
      id: '/api/public/perks/verify'
      path: '/api/public/perks/verify'
      fullPath: '/api/public/perks/verify'
      preLoaderRoute: typeof ApiPublicPerksVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mogul-bonuses/$slug': {
      id: '/api/public/mogul-bonuses/$slug'
      path: '/api/public/mogul-bonuses/$slug'
      fullPath: '/api/public/mogul-bonuses/$slug'
      preLoaderRoute: typeof ApiPublicMogulBonusesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/upsell-campaigns': {
      id: '/api/public/hooks/upsell-campaigns'
      path: '/api/public/hooks/upsell-campaigns'
      fullPath: '/api/public/hooks/upsell-campaigns'
      preLoaderRoute: typeof ApiPublicHooksUpsellCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trial-ending-reminder': {
      id: '/api/public/hooks/trial-ending-reminder'
      path: '/api/public/hooks/trial-ending-reminder'
      fullPath: '/api/public/hooks/trial-ending-reminder'
      preLoaderRoute: typeof ApiPublicHooksTrialEndingReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe': {
      id: '/api/public/hooks/stripe'
      path: '/api/public/hooks/stripe'
      fullPath: '/api/public/hooks/stripe'
      preLoaderRoute: typeof ApiPublicHooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/renewal-reminder': {
      id: '/api/public/hooks/renewal-reminder'
      path: '/api/public/hooks/renewal-reminder'
      fullPath: '/api/public/hooks/renewal-reminder'
      preLoaderRoute: typeof ApiPublicHooksRenewalReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reengagement': {
      id: '/api/public/hooks/reengagement'
      path: '/api/public/hooks/reengagement'
      fullPath: '/api/public/hooks/reengagement'
      preLoaderRoute: typeof ApiPublicHooksReengagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/morning-checkin-nudge': {
      id: '/api/public/hooks/morning-checkin-nudge'
      path: '/api/public/hooks/morning-checkin-nudge'
      fullPath: '/api/public/hooks/morning-checkin-nudge'
      preLoaderRoute: typeof ApiPublicHooksMorningCheckinNudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/medication-reminders': {
      id: '/api/public/hooks/medication-reminders'
      path: '/api/public/hooks/medication-reminders'
      fullPath: '/api/public/hooks/medication-reminders'
      preLoaderRoute: typeof ApiPublicHooksMedicationRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meal-reminders': {
      id: '/api/public/hooks/meal-reminders'
      path: '/api/public/hooks/meal-reminders'
      fullPath: '/api/public/hooks/meal-reminders'
      preLoaderRoute: typeof ApiPublicHooksMealRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-enqueue': {
      id: '/api/public/hooks/daily-enqueue'
      path: '/api/public/hooks/daily-enqueue'
      fullPath: '/api/public/hooks/daily-enqueue'
      preLoaderRoute: typeof ApiPublicHooksDailyEnqueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/coach-digest': {
      id: '/api/public/hooks/coach-digest'
      path: '/api/public/hooks/coach-digest'
      fullPath: '/api/public/hooks/coach-digest'
      preLoaderRoute: typeof ApiPublicHooksCoachDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/$provider/callback': {
      id: '/api/public/oauth/$provider/callback'
      path: '/api/public/oauth/$provider/callback'
      fullPath: '/api/public/oauth/$provider/callback'
      preLoaderRoute: typeof ApiPublicOauthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCoachingRoute: typeof AdminCoachingRoute
  AdminConsultRoute: typeof AdminConsultRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCourseRoute: typeof AdminCourseRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminMealsRoute: typeof AdminMealsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMoneyRoute: typeof AdminMoneyRoute
  AdminPerksRoute: typeof AdminPerksRoute
  AdminPinRoute: typeof AdminPinRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUpsellEmailsRoute: typeof AdminUpsellEmailsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminCoachingRoute: AdminCoachingRoute,
  AdminConsultRoute: AdminConsultRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCourseRoute: AdminCourseRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminMealsRoute: AdminMealsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMoneyRoute: AdminMoneyRoute,
  AdminPerksRoute: AdminPerksRoute,
  AdminPinRoute: AdminPinRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUpsellEmailsRoute: AdminUpsellEmailsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCheckinRouteChildren {
  AppCheckinTodayRoute: typeof AppCheckinTodayRoute
}

const AppCheckinRouteChildren: AppCheckinRouteChildren = {
  AppCheckinTodayRoute: AppCheckinTodayRoute,
}

const AppCheckinRouteWithChildren = AppCheckinRoute._addFileChildren(
  AppCheckinRouteChildren,
)

interface AppNutritionRouteChildren {
  AppNutritionSlugRoute: typeof AppNutritionSlugRoute
  AppNutritionAcademyRoute: typeof AppNutritionAcademyRoute
  AppNutritionMogulBonusesRoute: typeof AppNutritionMogulBonusesRoute
  AppNutritionLessonsSlugRoute: typeof AppNutritionLessonsSlugRoute
}

const AppNutritionRouteChildren: AppNutritionRouteChildren = {
  AppNutritionSlugRoute: AppNutritionSlugRoute,
  AppNutritionAcademyRoute: AppNutritionAcademyRoute,
  AppNutritionMogulBonusesRoute: AppNutritionMogulBonusesRoute,
  AppNutritionLessonsSlugRoute: AppNutritionLessonsSlugRoute,
}

const AppNutritionRouteWithChildren = AppNutritionRoute._addFileChildren(
  AppNutritionRouteChildren,
)

interface AppProtocolRouteChildren {
  AppProtocolHistoryRoute: typeof AppProtocolHistoryRoute
}

const AppProtocolRouteChildren: AppProtocolRouteChildren = {
  AppProtocolHistoryRoute: AppProtocolHistoryRoute,
}

const AppProtocolRouteWithChildren = AppProtocolRoute._addFileChildren(
  AppProtocolRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBreatheRoute: typeof AppBreatheRoute
  AppCheckinRoute: typeof AppCheckinRouteWithChildren
  AppCoachRoute: typeof AppCoachRoute
  AppGenderRequiredRoute: typeof AppGenderRequiredRoute
  AppIdentityRoute: typeof AppIdentityRoute
  AppJournalRoute: typeof AppJournalRoute
  AppLabsRoute: typeof AppLabsRoute
  AppNutritionRoute: typeof AppNutritionRouteWithChildren
  AppOutdoorRoute: typeof AppOutdoorRoute
  AppPeptidesRoute: typeof AppPeptidesRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProgressRoute: typeof AppProgressRoute
  AppProtocolRoute: typeof AppProtocolRouteWithChildren
  AppReadinessRoute: typeof AppReadinessRoute
  AppRedeemRoute: typeof AppRedeemRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpiritRoute: typeof AppSpiritRoute
  AppTodayRoute: typeof AppTodayRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConsultApplyRoute: typeof AppConsultApplyRoute
  AppConsultSeatRoute: typeof AppConsultSeatRoute
  AppMirrorIdRoute: typeof AppMirrorIdRoute
  AppConsultIndexRoute: typeof AppConsultIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAchievementsRoute: AppAchievementsRoute,
  AppBillingRoute: AppBillingRoute,
  AppBreatheRoute: AppBreatheRoute,
  AppCheckinRoute: AppCheckinRouteWithChildren,
  AppCoachRoute: AppCoachRoute,
  AppGenderRequiredRoute: AppGenderRequiredRoute,
  AppIdentityRoute: AppIdentityRoute,
  AppJournalRoute: AppJournalRoute,
  AppLabsRoute: AppLabsRoute,
  AppNutritionRoute: AppNutritionRouteWithChildren,
  AppOutdoorRoute: AppOutdoorRoute,
  AppPeptidesRoute: AppPeptidesRoute,
  AppPlanRoute: AppPlanRoute,
  AppProgressRoute: AppProgressRoute,
  AppProtocolRoute: AppProtocolRouteWithChildren,
  AppReadinessRoute: AppReadinessRoute,
  AppRedeemRoute: AppRedeemRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSpiritRoute: AppSpiritRoute,
  AppTodayRoute: AppTodayRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppConsultApplyRoute: AppConsultApplyRoute,
  AppConsultSeatRoute: AppConsultSeatRoute,
  AppMirrorIdRoute: AppMirrorIdRoute,
  AppConsultIndexRoute: AppConsultIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CourseRoute: CourseRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  QaRoute: QaRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScreenerFailRoute: ScreenerFailRoute,
  SubscribeRoute: SubscribeRoute,
  TermsRoute: TermsRoute,
  DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute:
    DotwellKnownAppleDeveloperMerchantidDomainAssociationRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicCollectRoute: ApiPublicCollectRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksCoachDigestRoute: ApiPublicHooksCoachDigestRoute,
  ApiPublicHooksDailyEnqueueRoute: ApiPublicHooksDailyEnqueueRoute,
  ApiPublicHooksMealRemindersRoute: ApiPublicHooksMealRemindersRoute,
  ApiPublicHooksMedicationRemindersRoute:
    ApiPublicHooksMedicationRemindersRoute,
  ApiPublicHooksMorningCheckinNudgeRoute:
    ApiPublicHooksMorningCheckinNudgeRoute,
  ApiPublicHooksReengagementRoute: ApiPublicHooksReengagementRoute,
  ApiPublicHooksRenewalReminderRoute: ApiPublicHooksRenewalReminderRoute,
  ApiPublicHooksStripeRoute: ApiPublicHooksStripeRoute,
  ApiPublicHooksTrialEndingReminderRoute:
    ApiPublicHooksTrialEndingReminderRoute,
  ApiPublicHooksUpsellCampaignsRoute: ApiPublicHooksUpsellCampaignsRoute,
  ApiPublicMogulBonusesSlugRoute: ApiPublicMogulBonusesSlugRoute,
  ApiPublicPerksVerifyRoute: ApiPublicPerksVerifyRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicOauthProviderCallbackRoute: ApiPublicOauthProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
