// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

async function resolveAccessToken(): Promise<string | undefined> {
  // First try: cached session (cheap, sync-ish).
  const { data } = await supabase.auth.getSession()
  if (data.session?.access_token) return data.session.access_token

  // On a hard reload the session may still be restoring from storage.
  // Wait briefly for onAuthStateChange to fire before giving up.
  if (typeof window === 'undefined') return undefined
  return new Promise<string | undefined>((resolve) => {
    let done = false
    const sub = supabase.auth.onAuthStateChange((_e, session) => {
      if (done) return
      if (session?.access_token) {
        done = true
        sub.data.subscription.unsubscribe()
        clearTimeout(timer)
        resolve(session.access_token)
      }
    })
    const timer = setTimeout(() => {
      if (done) return
      done = true
      sub.data.subscription.unsubscribe()
      resolve(undefined)
    }, 1500)
  })
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const token = await resolveAccessToken()
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
